# yml 파일: yaml(야믈) 파일, 스프링부트의 환경을 설정하는 파일
# 주의: 단계를 tab으로 구분

# 포트번호 설정
# 프로젝트 실행 경로 설정 - 루트 경로가 /에서 /BookMarket으로 변경함
server:
  port: 8090
  servlet:
    context-path: /CampingMarket
parsing:
  application:
    name: CampingMarket

# 파일 업로드 위치 설정
file:
  uploadDir: D:/upload/images/

# log4j2 라이브러리 위치 설정
logging:
  config: classpath:logging/log4j2.xml


# Spring Boot 설정
spring:
  # 제약사항 애너테이션의 메시지 설정
  message:
    encoding: UTF-8
    basename: messages
  servlet:
    encoding:
      force-response: true
  # HTTP 요청 방식으로 GET, POST, PUT, DELETE를 적용하는 설정
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    # 파일 업로드 설정
    multipart:
      enabled: true
      file-size-threshold: 2KB
      location: D:/upload/images
      max-file-size: 200MB
      max-request-size: 200MB
  # devtools 기능 활성화
  devtools:
    livereload:
      enabled: true
  # 타임리프 자동 리로드 기능 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  # sql을 실행할 때 매번 새로 초기화
  sql:
    init:
      mode: always
  jpa:
    # 테이블 생성
    hibernate:
      ddl-auto: update
    # 생성할 때 sql문을 보여줌
    show-sql: true
    # sql문을 보기좋게 정리
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성후에 data.sql 파일 실행
    defer-datasource-initialization: true

  # MySQL DB 환경 설정
  # db01 -> JSP(회원게시판)과 연결
  # db02 -> 스프링부트(블로그앱)과 연결
  # db03 -> 스프링부트(도서 쇼핑몰)과 연결
  # db04 -> 스프링부트(팀별로 제작하는 쇼핑몰)과 연결
  datasource:
    url: jdbc:mysql://localhost:3306/db04
    driverClassName: com.mysql.cj.jdbc.Driver
    username: human01
    password: 1234
